---
title: "Exercise 1: Time Series Forecasting"
author: "Chris Mainey"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load data

```{r loaddt}
#ae_uk <- read.csv("data/ae_uk.csv")
#ae_uk$arrival_time <- datetime(ae_uk$arrival_time)
library(readr)
ae_uk <- read_csv("data/ae_uk.csv", 
                  col_types = cols(arrival_time = col_datetime(format = "%d/%m/%Y %H:%M")))

head(ae_uk)
```



```{r loadpackages, message=FALSE, include=FALSE}
lapply(c("ggplot2", "tidyr", "dplyr", "lubridate", "tsibble", "scales"),require, character.only=TRUE)

```

```{r visualize, warning=FALSE}
ae_uk %>% 
  select(gender, type_injury) %>% 
  #add_count(name = "ct") %>% 
  gather("key", "value") %>% 
  mutate(key = factor(key, levels = c("gender", "type_injury"), ordered = TRUE),
         value = factor(value, levels=c("male", "female", "minor", "major"), ordered = TRUE)) %>%   ggplot(aes(x=value, fill=key))+
    geom_bar(alpha=0.5, col=1)
    

```


## Make tsibble

```{r duplicated}

ae_uk %>%  duplicated() %>% sum() # check
ae_wd <- ae_uk %>% distinct()

ae_tsb <- ae_wd %>%  #create tsibble
  as_tsibble(key=c(gender, type_injury), index = arrival_time, regular=FALSE)

# 
ae_hourly <- ae_tsb %>% group_by(gender, type_injury) %>% 
  index_by(arrival_1h = floor_date(arrival_time, "1 hour")) %>% 
             summarise(n_attendance = n())

           
           
has_gaps(ae_hourly)
scan_gaps(ae_hourly)
count_gaps(ae_hourly)

ae_hourly <-ae_tsb %>%  group_by(gender, type_injury) %>% 
  index_by(arrival_1h = floor_date(arrival_time, "1 hour")) %>% 
  summarise(n_attendance = n()) %>% fill_gaps(n_attendance=0L) %>%  ungroup()

ae_daily <-ae_tsb %>%  group_by(type_injury) %>% 
  filter(type_injury == "major" ) %>% 
  index_by(arrival_1d = day(arrival_time)) %>% 
  summarise(n_attendance = n()) %>% fill_gaps(n_attendance=0L) %>%  ungroup()


```

## Plots

```{r autoplot1}
library(fabletools)
ae_hourly %>% autoplot(n_attendance)

```

```{r plots2, eval=FALSE}
#library(feasts)

# None of this runs, FIX IT!

ae_hourly %>% gg_season(period = "month")


ae_hourly %>% 
  filter_index("2014"~"2016") %>% 
  gg_season(period = "month")


ae_daily %>%  gg_tsdisplay()

ae_daily %>%  features (n_attendance, ljun_box, dof = 0)

ae_daily <- ae_hourly %>% 
  index_by(year_day=as_date(arrival_1h)) %>% 
  summarise(n_attendance=sum(n_attendance))


```


---
# Simple forcasting

```{r simple1}
library(fable)

ae_fit <- ae_daily %>% 
  model( mean = MEAN(n_attendance)
         , naive = NAIVE(n_attendance)
         , snaive = SNAIVE(n_attendance, lag="year")
         , drift = RW(n_attendance ~ drift())
        )

ae_fit %>% glance()
ae_fit

```

```{r forecast}
library(fabletools)
library(fable)
ae_fc <- ae_fit %>% 
  forecast(h = "30 days")

# Plot
ae_fc %>% autoplot(filter_index(ae_daily, "2016"~.), level=NULL)

```

## Fit and residual
```{r fitresid}
# Fitted
ae_fit %>% augment() %>% filter(.model=="snaive") %>%  select(.fitted) %>%  autoplot()
# Residuals
ae_fit %>% augment() %>% filter(.model=="snaive") %>%  select(.resid) %>% plot()



```